<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle(GetMessage("DEMO_IBLOCK_ESTORE_REVIEWS_TITLE"));
?><?$APPLICATION->IncludeComponent("bitrix:news", ".default", Array(
	"IBLOCK_TYPE"	=>	"books",
	"IBLOCK_ID"	=>	"#IBLOCK.ID(XML_ID=books-reviews)#",
	"NEWS_COUNT"	=>	"10",
	"USE_SEARCH"	=>	"Y",
	"USE_RSS"	=>	"Y",
	"NUM_NEWS"	=>	"20",
	"NUM_DAYS"	=>	"360",
	"YANDEX"	=>	"N",
	"USE_RATING"	=>	"Y",
	"MAX_VOTE"	=>	"5",
	"VOTE_NAMES"	=>	array(
		0	=>	"",
		1	=>	"1",
		2	=>	"2",
		3	=>	"3",
		4	=>	"4",
		5	=>	"5",
	),
	"USE_CATEGORIES"	=>	"N",
	"USE_REVIEW"	=>	"N",
	"USE_FILTER"	=>	"N",
	"SORT_BY1"	=>	"ACTIVE_FROM",
	"SORT_ORDER1"	=>	"DESC",
	"SORT_BY2"	=>	"SORT",
	"SORT_ORDER2"	=>	"ASC",
	"SEF_MODE"	=>	"N",
	"CACHE_TYPE"	=>	"A",
	"CACHE_TIME"	=>	"3600",
	"CACHE_FILTER"	=>	"N",
	"DISPLAY_PANEL"	=>	"Y",
	"SET_TITLE"	=>	"Y",
	"INCLUDE_IBLOCK_INTO_CHAIN"	=>	"N",
	"ADD_SECTIONS_CHAIN"	=>	"Y",
	"USE_PERMISSIONS"	=>	"N",
	"META_KEYWORDS"	=>	"-",
	"META_DESCRIPTION"	=>	"-",
	"DETAIL_ACTIVE_DATE_FORMAT"	=>	"d.m.Y",
	"DETAIL_FIELD_CODE"	=>	array(
		0	=>	"",
	),
	"DETAIL_PROPERTY_CODE"	=>	array(
		0	=>	"BOOK",
		1	=>	"AUTHOR",
		2	=>	"rating",
	),
	"PREVIEW_TRUNCATE_LEN"	=>	"0",
	"LIST_ACTIVE_DATE_FORMAT"	=>	"d.m.Y",
	"LIST_FIELD_CODE"	=>	array(
		0	=>	"",
	),
	"LIST_PROPERTY_CODE"	=>	array(
		0	=>	"",
	),
	"HIDE_LINK_WHEN_NO_DETAIL"	=>	"N",
	"DETAIL_DISPLAY_TOP_PAGER"	=>	"N",
	"DETAIL_DISPLAY_BOTTOM_PAGER"	=>	"Y",
	"DETAIL_PAGER_TITLE"	=>	GetMessage("DEMO_IBLOCK_ESTORE_REVIEWS_DETAIL_PAGER_TITLE"),
	"DISPLAY_TOP_PAGER"	=>	"N",
	"DISPLAY_BOTTOM_PAGER"	=>	"Y",
	"PAGER_TITLE"	=>	GetMessage("DEMO_IBLOCK_ESTORE_REVIEWS_PAGER_TITLE"),
	"PAGER_SHOW_ALWAYS"	=>	"N",
	"PAGER_DESC_NUMBERING"	=>	"N",
	"PAGER_DESC_NUMBERING_CACHE_TIME"	=>	"36000",
	"VARIABLE_ALIASES"	=>	array(
		"SECTION_ID"	=>	"SECTION_ID",
		"ELEMENT_ID"	=>	"REVIEW",
	)
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>