<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Комнатные термостаты SONDER - принцип работы  и обзор моделей.");
?> 
<table width="940"> 
  <tbody> 
    <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"> 
        <div style="text-align: center;"> 
          <h2>Комнатные термостаты SONDER - принцип работы и обзор моделей.</h2>
         </div>
       
        <div style="text-align: right;"><i><font size="2">&quot;Жарко в комнатах натоплено. 
              <br />
             Да мелко сыплется за ворот нехороший холодок.&quot; 
              <br />
             А. Башлачёв</font></i></div>
       
        <br />
       
        <p>Так уж устроен человек, что летом ему хочется живительной прохлады, зимой же, когда этой прохлады хоть отбавляй, мечтается об уютном тёплом доме и большой кружке душистого горячего чая. Конечно, можно решать вопросы терморегуляции в своём доме и самостоятельно, попеременно открывая - закрывая форточки, скрипя вентилями батарей, перетаскивая из угла в угол прожорливые электрообогреватели... Наши бабушки и дедушки оставили нам много житейских рецептов на этот счёт, но, следуя только им, мы рискуем понапрасну потратить то драгоценное время, которое могли бы с пользой провести сидя в &quot;ВКонтакте&quot; или наблюдая за перипетиями очередного телешоу. К счастью, уже довольно давно изобретены и с успехом применяются такие замечательные устройства, как термостаты. Существуют различные способы классификации этих устройств в зависимости от их конструктивных особенностей и областей применения. В частности, термостаты можно сгруппировать на промышленные и комнатные. Сразу оговоримся, что в этой статье нас будет интересовать исключительно последний их тип. Более того, чтобы стать героем данного рассказа, недостаточно быть просто любым комнатным термостатом, для этого надо быть механическим термостатом, к тому же произведённым компанией <b><a href="http://www.sonder-regulacion.com" target="_blank">SONDER</a></b>. И теперь немного о ней.</p>
       
        <table> 
          <tbody> 
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"> 
                <p>История этой компании насчитывает уже почти полвека. Изначально она входила в международную группу &quot;<b>SOPAC Regulacion, SA</b>&quot; (Франция), но через двадцать лет обособилась под испанским флагом и под названием &quot;<b>Sonder Regulacion</b>&quot;, а ещё через десятилетие обзавелась и новыми производственными площадями. Термостаты всегда были одним из основных продуктов компании <b>SONDER</b>. Большой опыт в их производстве и то повышенное внимание к исследовательской работе, которое отличает данного производителя, позволяют нам говорить о высоком качестве обсуждаемых устройств.</p>
               </td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="300" height="220" src="/images/articles/sonder_ta/sonder_office.jpg" /></td> </tr>
           </tbody>
         </table>
       
        <p>Несмотря на то, что последнее время приоритетным в деятельности компании считается изготовление терморегулирующего оборудования для промышленности, комнатные термостаты у <b>SONDER</b> представлены тоже весьма широко, и найти среди них подходящий именно вам не составит особого труда. Производство данной компании разделено на два технологических потока, один из которых посвящён механическим, а другой электронным устройствам. Комнатные термостаты, которые вы сможете обнаружить в каталоге <b>SONDER</b>, соответственно, будут представлены в обоих этих категориях. Но, поскольку наша компания <b><a target="_blank" href="http://www.poligon.info">&quot;ПОЛИГОН&quot;</a></b> сосредоточена, в основном, на дестрибьюции именно механических термостатов <b>SONDER</b>, то и детальному рассмотрению в рамках текущего повествования будут подвергнуты именно они.</p>
       
        <table> 
          <tbody> 
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/membrana.jpg" /></td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"> 
                <p>В основании конструкции механического термостата находится газовая мембрана. Газ, заключённый внутри мембраны при изменении температуры изменяет свой объём, вызывая тем самым изменение положения стенок мембраны. Стенки мембраны, в свою очередь, воздействуют на механизм замыкания контактов электрической цепи, осуществляющей питание подключённых к ней обогревательных или же, напротив, охлаждающих систем.</p>
               </td> </tr>
           </tbody>
         </table>
       
        <p>Управляющий элемент с насадкой в виде колесика со шкалой прикрепляется к одной из стенок мембраны и фиксирует её, задавая тем самым то пороговое положение, при достижении которого противоположная стенка сможет воздействовать на замыкающие контакты. Пользователь устанавливает желаемую температуру ВОЗДУХА (это важно!) в помещении, и в соответствии с этой температурой термостат производит подключение и отключение, например, газового котла или электрообогревателя.</p>
       
        <p>Ни для кого не секрет, что и газовые котлы, и многие электрические обогреватели имеют собственные встроенные термостаты, позволяющие ставить активацию этих устройств в зависимость от показателей температуры. Но в этом случае речь будет идти о температуре рабочего вещества устройства, а она соотносится со средней  температурой в помещении весьма нелинейно. Как следствие, происходит менее рациональное расходование топлива или электричества, более частые включения-отключения систем, что приводит к снижению износостойкости оборудования, и, конечно, в результате мы имеем гораздо менее эффективное управление микроклиматом в помещении. Совсем иначе обстоят дела при использовании комнатных термостатов. По правилам их установка производится непосредственно в помещении, на значительном удалении от любых источников, способных исказить объективные показатели температуры воздуха, будь то окна, бытовые электроприборы, компьютеры,  батареи отопительных систем, кондиционеры и так далее. Такое размещение позволяет термостату управлять отопительными либо охлаждающими системами, опираясь на реальный уровень тепла в помещении, который-то и интересует в конечном счёте пользователя. Очевидно, при таком подходе и расход энергии или топлива, и частота включений управляемого оборудования станут более оптимальны. На практике, речь может идти о повышении эффективности упомянутого оборудования до <b>30%</b>.</p>
       
        <table> 
          <tbody> 
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"> 
                <p>Теперь, когда ваши сомнения насчёт оправданности использования комнатных термостатов <b>SONDER</b> безусловно отпали, предлагаем вам ознакомиться со всеми доступными на сегодняшний день моделями этих устройств. Каждый термостат содержит в своём названии латинские буквы TA, что является аббревиатурой словосочетания &quot;Thermostat Ambient&quot;, то есть по-русски - &quot;комнатный термостат&quot;. Производитель разделил свои комнатные термостаты на две серии - &quot;тысячную&quot; и &quot;трёхтысячную&quot;.</p>
               </td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/sonder_logo.jpg" /> </td> </tr>
           </tbody>
         </table>
       
        <p>&quot;Тысячная&quot; серия характеризуется как &quot;базовая&quot;, и включает в себя три модели:</p>
       
        <table> 
          <tbody> 
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a target="_blank" href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73425"><b>TA 1002</b></a> - простой термостат с возможностью выбора желаемой температуры от +6 до +30 градусов по Цельсию. Принцип включения управляемого устройства &quot;всё или ничего&quot;, то есть &quot;потеплело - остужаем, похолодало - нагреваем&quot;.</td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta1002.scheme.jpg" /> </td> </tr>
           
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73426" target="_blank"><b>TA 1007</b></a> - помимо функций предыдущего термостата имеет кнопку его отключения и световой индикатор работы управляемого устройства.</td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta1007.scheme.jpg" /></td> </tr>
           
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73427" target="_blank"><b>TA 1008</b></a> - этот термостат позволит выбрать условие срабатывания термостата - при потеплении либо при похолодании. В нейтральном положении устройство выключено.</td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta1008.scheme.jpg" /></td> </tr>
           </tbody>
         </table>
       
        <p>&quot;Трёхтысячная&quot; серия представляется производителем как &quot;расширенная&quot;. Она включает девять элементов, три из которых являются полными функциональными аналогами &quot;базовых&quot; устройств. Помимо количества элементов, &quot;трёхтысячная&quot; серия отличается от &quot;базовой&quot; тем, что заключена в корпус другого вида и снабжена опциональной пластиковой рамкой для более удобного настенного монтажа. Представители &quot;трёхтысячной&quot; серии в списке ниже:</p>
       
        <table> 
          <tbody> 
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73428" target="_blank"><b>TA 3002</b></a> - аналогична <a target="_blank" href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73425"><b>TA 1002</b></a></td><td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta3002.scheme.jpg" /></td> </tr>
           
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73429" target="_blank"><b>TA 3005</b></a> - к функционалу предыдущего термостата здесь добавлена индикация работы управляемого устройства. </td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta3005.scheme.jpg" /></td> </tr>
           
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73430" target="_blank"><b>TA 3006</b></a> - создан специально для электрического подогрева полов. В отличие от <b><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73428" target="_blank">TA 3002</a></b> и <a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73425" target="_blank"><b>TA 1002</b></a> он обладает так называемым бустером, то есть встроенным непосредственно в корпус термостата нагревательным элементом.</td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta3006.scheme.jpg" /></td> </tr>
           
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73431" target="_blank"><b>TA 3007</b></a> - функционально аналогичен <a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73426" target="_blank"><b>TA 1007</b></a>.</td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta3007.scheme.jpg" /></td> </tr>
           
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73432" target="_blank"><b>TA 3008</b></a> - функционально аналогичен <a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73427" target="_blank"><b>TA 1008</b></a>.</td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta3008.scheme.jpg" /></td> </tr>
           
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73433" target="_blank"><b>TA 3010</b></a> - здесь ко всем функциям <b><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73432" target="_blank">TA 3008</a></b> (<a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73427" target="_blank"><b>TA 1008</b></a>) ещё добавляется возможность двухпозиционного управления вентилятором. </td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta3010.scheme.jpg" /></td> </tr>
           
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73434" target="_blank"><b>TA 3012</b></a> - это уже прибор с &quot;расширенной&quot; маршрутизацией. Трёхпозиционный переключатель в среднем &quot;дневном&quot; положении заставляет устройство функционировать как обычный <a target="_blank" href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73425"><b>TA 1002</b></a> (<b><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73428" target="_blank">TA 3002</a></b>). В &quot;ночной&quot; позиции схема дополняется бустерным встроенным нагревателем, превращая наш термостат из <b><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73434" target="_blank">TA 3012</a></b> в <b><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73430" target="_blank">TA 3006</a></b>, что приводит к более раннему отключению обогревательной системы. И, наконец, в третьем режиме термостат работает так же по &quot;ночной&quot; схеме, но только переходит к ней в заданные таймером промежутки времени.</td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta3012.scheme.jpg" /></td> </tr>
           
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73435" target="_blank"><b>TA 3014</b></a> - это просто гибрид <a target="_blank" href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73425"><b>TA 1002</b></a> (<b><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73428" target="_blank">TA 3002</a></b>) и независимого пульта управления 3-х скоростным вентилятором. Вы можете легко убедиться в этом сами, просто посмотрев на приведённую ниже схему.</td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta3014.scheme.jpg" /></td> </tr>
           
            <tr> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73436" target="_blank"><b>TA 3015</b></a> - в отличие от <b><a href="/catalog/index.php?SECTION_ID=5536&amp;ELEMENT_ID=73435" target="_blank">TA 3014</a></b> включение вентилятора и управление его скоростями будет доступно только в режиме &quot;охлаждения&quot;.</td> <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none;"><img width="200px" src="/images/articles/sonder_ta/ta3015.scheme.jpg" /></td> </tr>
           </tbody>
         </table>
       
        <p>Безусловно, наиболее часто комнатные термостаты используются в связке с газовыми котлами. Из-за очевидной выгоды такого союза многие производители современных газовых котлов конструктивно предусматривают специальные клеммы для подключения внешних комнатных термостатов. Эти клеммы, как правило, изначально соединены проволочной перемычкой. Для того, чтобы их отыскать, воспользуйтесь руководством пользователя, прилагаемого к газовому котлу. Иногда проблема решается звонком <s>другу</s> в организацию, продавшую вам котёл, а совсем в экстремальных случаях - заменой морально устаревшего котла на актуальный.</p>
       
        <p>Так же часто комнатные термостаты подключают к электрическим обогревателям. В этом случае комнатный термостат включается в разрыв электрической цепи, питающей обогреватель, что весьма очевидно. Столь же очевидным представляется и полное обесточивание электросети перед проведением монтажных работ по установке и подключению вашего нового комнатного термостата. В том же, что он у вас появится вскоре после прочтения данной статьи, наша компания <b><a target="_blank" href="http://www.poligon.info">&quot;ПОЛИГОН&quot;</a></b>, которая давно и успешно торгует продукцией <b>SONDER</b> в России, уже ничуть не сомневается. </p>
       </td></tr>
   </tbody>
 </table>
 <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>