<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Реле контроля однофазного тока TELE G2IW5A10 230VAC");?> 
<h2 align="center"><span class="style11"><strong>Реле контроля тока G2IW5A10 230VAC TELE </strong></span></h2>Tele. Technik braucht kontrolle. <br /><table cellspacing="0" cellpadding="0" border="0" width="600"> <tbody> 	<tr><td><b><font size="3">G2IW5A10 230VAC реле контроля однофазного тока <br />Пр-во: TELE (Австрия)<br /></font></b> </td><td> 		<table cellspacing="0" cellpadding="6" bordercolor="#39b54a" border="2" align="right"> 		<tbody> 		<tr><td> 		<div align="center"><font size="5" face="Arial" color="#39b54a"><b>В наличии</b></font> </div>		<font size="5" face="Arial" color="#ff0000"><b>3246,00руб </b></font><font color="#339966"></font></td></tr>	</tbody>
	</table></td>
	</tr></tbody></table>
<ul class="mark" style="font-size: 120%;"> 	<li><b>Функция контроля однофазного тока в окне</b> (между min и max) </li>	<li>Регулируемые пороги срабатывания </li>	<li><b>3 диапазона измерения тока</b> в одном устройстве(In): 1-20мА, 0,05-1A, 0,25-5A (AC/DC). </li>	<li>Регулируемая задержка срабатывания (от 0,2 до 10с) </li>	<li>1 перекидной контакт 250VAC/5A </li>	<li>Монтаж на DIN-рейку, корпус IP40, ширина 22,5мм </li>	<li><b>Разработка и производство: Австрия</b>; ISO 9001; ISO 14001; RoHS-WEEE, ГОСТ </li>	<li>Напряжение питания 230VAC (определяется модулем TR2)</li>	<li>Промышленное исполнение </li></ul>

<table> 	<tbody>    <tr><td> <span class="style11">Диапазоны регулировки: </span> 	<table cellspacing="0" cellpadding="0" bordercolor="#cccccc" border="1"> 		<tbody> 		<tr> <td width="215" valign="top" class="style11">Верхний порог срабатывания</td> <td width="171" valign="top" class="style11">от 10% до 100% от In*</td> </tr>		<tr> <td valign="top" class="style11"><p>Нижний порог срабатывания </p></td> <td valign="top" class="style11">от 5% до 95% от In*</td> </tr>		<tr> <td valign="top" class="style11">Задержка срабатывания</td> <td valign="top" class="style11">от 0,2 до 10с</td> </tr>		<tr><td valign="top" class="style11">Напряжение питания</td> <td valign="top" class="style11">230VAC*</td></tr>		</tbody>	</table>	<span class="style12">* In = 20мА, 1А или 5А 	<br />    * напряжение питания определяется модулем питания TR2: от 12 до 400V. Модули в наличии. 	<br />	<br />	</span> 	<p><span class="style11"><strong>Устройство в наличии с модулем питания 230VAC на складе в Санкт-Петербурге в количестве менее 300шт</strong> (октябрь 2011) 	<br /><br /><br />
	<strong>Модули питания TR2</strong> выпускаются на следующие напряжения: 	<br />	12, 24, 42, 48, 110, 127, 230, 400<strong> VAC</strong>. 	<br />	<br />	<strong>Почему TELE:</strong> высочайшая надежность, австрийское качество, мировой лидер в области релейной автоматики (2 место в мире по количеству выпускаемых реле времени и реле контроля), более 47 лет разработки и производства реле контроля. 	<br />   Доставка Автотрейдингом, экспресс-почтой или в офисах партнеров в городах РФ. В наличии на складе. 	<br />	<br />   <font size="4"><strong>Техническая документация G2IW5A10:</strong></font> <a class="pdf" href="/PDF/TELE/en_g2iw5a10.pdf"> </a> 	<br />	<br />	<strong><font size="4">Специальная акция:</font></strong><br />
	<strong><font size="3">реле контроля тока G2IW5A10 промышленной серии GAMMA с модулем питания TR2 230VAC </font> 
	<br />    со скидкой 20% при заказе любого количества. 	<br />	<font size="4">4058 руб -&gt; <font color="#ff0000"><span class="style10">3246 руб с НДС</span></font></font></strong></span>	<br />	(действительно для находящейся на складе партии товара)<strong> 	<br />	<br />	Адреса партнеров в городах РФ: 	<br />	<a href="http://www.tele-power-net.ru/contact.php">http://www.tele-power-net.ru/contact.php</a></strong></p>
	<p>Смотрите также все <a href="/catalog/index.php?SECTION_ID=157">реле контроля от TELE</a>.</p>	</td> 
	<td valign="top"><img height="455" width="300" src="/images/TELE/G2IW5A10_R_.jpg" alt="реле контроля тока однофазное G2IW5A10" /> 	<br />		<img height="183" width="300" src="/images/TELE/G2PM400VSY20_dim.jpg" alt="размеры реле контроля тока G2IW5A10" /> 		<br />		<img height="144" width="300" src="/images/TELE/G2IW5A10_digram.jpg" alt="Диаграмма реле контроля тока G2IW5A10" /> </td> </tr>	</tbody></table>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>