<?
$MESS["FS_ERROR1"] = "В поисковой фразе обнаружена ошибка:";
$MESS["FS_ERROR2"] = "Исправьте поисковую фразу и повторите поиск.";
$MESS["FS_SYNTAX1"] = "Синтаксис поискового запроса:";
$MESS["FS_SYNTAX2"] = "Обычно запрос представляет из себя просто одно или несколько слов, например: <br>	<i>контактная информация</i><br> По такому запросу будут найдены страницы, на которых встречаются оба слова запроса. <br><br> Логические операторы позволяют строить более сложные запросы, например: <br> <i>контактная информация или телефон</i><br> По такому запросу будут найдены страницы, на которых встречаются либо слова &quot;контактная&quot; и &quot;информация&quot;, либо слово &quot;телефон&quot;.<br><br> <i>контактная информация не телефон</i><br> По такому запросу будут найдены страницы, на которых встречаются либо слова &quot;контактная&quot; и &quot;информация&quot;, но не встречается слово &quot;телефон&quot;.<br> Вы можете использовать скобки для построения более сложных запросов.<br><br> <b>Логические операторы:</b> <table border=\"0\" cellpadding=\"5\"><tr><td align=\"center\" valign=\"top\"><font class=\"text\">Оператор</font></td><td valign=\"top\"><font class=\"text\">Синонимы</font></td><td><font class=\"text\">Описание</font></td></tr><tr><td align=\"center\" valign=\"top\"><font class=\"text\">и</font></td><td valign=\"top\"><font class=\"text\">and, &, +</font></td><td><font class=\"text\">Оператор <i>логическое &quot;и&quot;</i> подразумевается, его можно опускать: запрос &quot;контактная информация&quot; полностью эквивалентен запросу &quot;контактная и информация&quot;.</font></td></tr><tr><td align=\"center\" valign=\"top\"><font class=\"text\">или</font></td><td valign=\"top\"><font class=\"text\">or, |</font></td><td><font class=\"text\">Оператор <i>логическое &quot;или&quot;</i> позволяет искать товары, содержащие хотя бы один из операндов. </font></td></tr><tr><td align=\"center\" valign=\"top\"><font class=\"text\">не</font></td><td valign=\"top\"><font class=\"text\">not, ~</font></td><td><font class=\"text\">Оператор <i>логическое &quot;не&quot;</i> ограничивает поиск страниц, не содержащих слово, указанное после оператора. </font></td></tr><tr><td align=\"center\" valign=\"top\"><font class=\"text\">( )</font></td><td valign=\"top\"><font class=\"text\">&nbsp;</font></td><td><font class=\"text:\"><i>Круглые скобки</i> задают порядок действия логических операторов. </font></td></tr></table>";
$MESS["FS_RESULTS"] = "Результаты поиска";
$MESS["FS_SEARCH"] = "Искать";
$MESS["FS_NO_RESULTS"] = "Ничего не найдено. Попробуйте переформулировать запрос.";

$MESS["SEARCH_TITLE"] = "Поиск";
$MESS["KEYWORDS"] = "Ключевые слова";
$MESS["SEARCH_FORUMS"] = "Искать в форуме";
$MESS["ALL_FORUMS"] = "Все форумы";
?>