<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Ссылки на сайты родственных тематик");?><p><h2>Ссылки на сайты радиотехнической и смежных тематик:</h2><ul>
	<li><a href="index.php"><strong>&gt; Радиотехнические порталы, форумы</strong></a></li>	<li><a href="links2_scheme.php">Схемы, справочники, руководства, техническая документация, статьи, сертификация</a></li>	<li><a href="links3_repair.php">Ремонт</a></li>	<li><a href="links4_develop.php">Разработка, проектирование и производство РЭА, печатных плат </a></li>	<li><a href="links5_suppliers.php">Поставщики и дистрибьюторы электронных компонентов, оборудования, сопутствующих материалов</a></li>	<li><a href="links6_cat.php">Каталоги ссылок, доски объявлений</a></li>	<li><a href="links7_var.php">Разное</a></li>
</ul>
<table width="100%" border="0" cellspacing="5" cellpadding="1">	<tr bgcolor="#CCCCCC"><td colspan="2"><strong>Радиотехнические порталы, форумы</strong></td></tr>	<tr>
		<td><a href="http://www.electro-gid.ru"><img src="http://www.electro-gid.ru/img/button_portal_blue.gif" border="0" alt="Электротехнический портал Electro-Gid.ru: генераторы, электростанции, батареи" title="Электротехнический портал Electro-Gid.ru: генераторы, электростанции, батареи" width="88" height="31"></a></td>
		<td>Electro Gid</td>	</tr>	
	<tr>
		<td><!-- QRZ.RU banner start --><a href="http://www.qrz.ru/"><img src="http://www.qrz.ru/graphics/banners/small2.gif" style="width: 88px; height: 31px; border: 0px" alt="Сервер радиолюбителей России - схемы, документация, соревнования, дипломы, программы, форумы и многое другое!"></a><!-- QRZ.RU banner end --></td>
		<td>Сервер радиолюбителей России</td>	</tr>	<tr>		<td><a href="http://www.rlocman.ru/indexs.htm" target="_top"><img src="http://www.rlocman.ru/logo/rlbut1r.gif" alt="РадиоЛоцман - поисковая машина схем в www" style="width: 88px; height: 31px; border: 0px"></a></td>		<td>РадиоЛоцман - поисковая машина схем, каталог</td>	</tr>	<tr>		<td><a href="http://www.kazus.ru" ><strong>KAZUS.ru</strong></a></td>		<td>Свежие и интересные схемы радиолюбительских устройств (17000 схем). 720 000 даташитов и поиск по он-лайн складам. Ответы на часто задаваемые вопросы (FAQ) по электронике. Форум. </td>	</tr>	<tr>		<td><a href="http://www.radioradar.net"><img src="http://radioradar.net/_banners/button.gif" style="width: 88px; height: 31px; border: 0px"></a></td>		<td>RadioRadar - сайт как для профессиональных радиоинженеров, так и для начинающих радиолюбителей и всем тем, кто интересуется аспектами развития современной радиотехники и электроники. На сайте представлены: ежедневная подборка новостей электроники, технологий, разработок, новинок электронных компонентов, радиолюбительский раздел, статьи и обзоры изобретений, разделы &quot;Ремонт РЭА&quot;, &quot;Альбомы схем&quot;, &quot;Справочная&quot;, обзоры аудио- и видеотехники, измерительной аппаратуры, подборка радиотехнических программ, книги, журналы, каталог компаний, выставки, форум, файлообменник, и многое другое</td>	</tr>	<tr>		<td><strong><a href="http://www.radioweb.ru/">radioweb.ru</a></strong></td>
		<td>Информационно-поисковая система &quot;Радиодетали и цены&quot;.Поиск по наименованию. Предлагается рубрикатор фирм и предприятий данной отрасли с возможностью добавления своих данных. Доп. услуги по созданию и поддержанию веб-представительства.</td>	</tr>
	<tr>		<td><a href="http://www.techportal.ru"><img src="http://www.techportal.ru/img/88x31.gif" alt="Техпортал: интернет-каталог систем безопасности" style="width: 88px; height: 31px; border: 1px"></a></td>		<td><a href="http://www.techportal.ru" target="_blank" title="ОПС, CCTV, Домофоны, СКУД, Охрана периметров, Оповещение, Пожаротушение, АТС, Дымоудаление, СКС, Климатическое оборудование, Cистемы управления зданием, Инженерные средства защиты, Огнезащита, Досмотровое оборудование, Защита информации, Радиосвязь и навигация."><b>Специализированный портал по безопасности. </b></a>
		<a href="http://www.phonezone.ru"></a>
		<a href="http://www.techportal.ru/equipment">Классификатор оборудования</a>, 
		<a href="http://www.techportal.ru/company">компаний</a>, 
		<a href="http://www.techportal.ru/trademark">торговых марок</a>, 
		<a href="http://www.techportal.ru/resource">ссылок</a>, 
		<a href="http://job.techportal.ru/">работа</a>
		</td>	</tr>	<tr>		<td><a title="Справочники схемы, мануалы, САПР, поиск схем, форум, статьи по электроники, расчеты." href="http://www.radiomaster.ru/"><strong>radiomaster.ru</strong></a></td>		<td>Портал радилюбителей: схемы, САПР, документация, софт.</td>	</tr>	<tr>		<td><a href="http://affon.narod.ru"><strong>affon.narod.ru </strong></a></td>		<td>Радиотехника и Цифровая техника C++Builder6 PCI контроллеры USB LPT I2C Delphi ПЛИС AHDL VHDL </td>	</tr>	<tr>		<td><a href="http://www.elec.ru/" target="_blank"><img src="http://static.elec.ru/img/logo_elec.gif" style="width: 88px; height: 31px; border: 1px" alt="Elec.ru - Крупнейший интернет-портал электротехнического рынка России и стран СНГ"></a></td>		<td>
			<!-- Start Elec.ru code-->			<a href="http://www.elec.ru/" target="_blank">Elec.ru - Крупнейший интернет-портал электротехнического рынка России и стран СНГ. </a> <!-- End Elec.ru code --></td>	</tr>	<tr>		<td style="text-align: center;"><a target="_blank" href="http://trm2007.narod.ru/"><img src="http://trm2007.narod.ru/images/88x31pink.png"width="88" height="31" border="0" alt="Теле- РадиоМастер 2007" title="Схемы и сервисные инструкции видео и аудиотехники, мониторов, мобильных телефонов, DVD, радиотелефонов, принтеров, копиров, МФУ, фотоаппаратов, кондиционеров и др. БЕСПЛАТНО! Секреты ремонта, статьи, справочные данные, советы мастеров, объявления о неликвидах"></a></td>		<td>Схемы и сервисные инструкции видео и аудиотехники, мониторов, мобильных телефонов, DVD, радиотелефонов, принтеров, копиров, МФУ, фотоаппаратов, кондиционеров и др. БЕСПЛАТНО! Секреты ремонта, статьи, справочные данные, советы мастеров, объявления о неликвидах </td>	</tr></table>
<p><strong>Код ссылки для обмена <a href="exchange.php">здесь</a></strong>.</p>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>