<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Ссылки");?><p align="left">
<h3>Ссылки на сайты радиотехнической тематики:</h3><ul>
	<li><a href="index.php">&gt; Радиотехнические порталы, форумы</a></li>	<li><a href="links2_scheme.php">Схемы, справочники, руководства, техническая документация, статьи, сертификация</a></li>	<li><a href="links3_repair.php">Ремонт</a></li>	<li><a href="links4_develop.php">Разработка, проектирование и производство РЭА, печатных плат</a></li>	<li><a href="links5_suppliers.php"><strong>&gt; Поставщики и дистрибьюторы электронных компонентов, оборудования, сопутствующих материалов</strong></a></li>	<li><a href="links6_cat.php">Каталоги ссылок, доски объявлений</a></li>	<li><a href="links7_var.php">Разное</a></li></ul>

<table width="100%" border="0" cellspacing="5" cellpadding="1"><tr bgcolor="#CCCCCC">	<td colspan="2"><strong>Поставщики и дистрибьюторы электронных компонентов, оборудования, сопутствующих материалов </strong></td></tr>
<tr>
	 <td><a href="http://www.1057567.ru"><img src="http://www.1057567.ru/links/images/gid_ban.gif" alt="насосное оборудование отопительное оборудование трубопроводная арматура запорная арматура задвижки фланцы тепловые завесы тепловые пушки бойлеры" border="0"></a></td>
	 <td>Продаем недорого <a href="http://www.1057567.ru/zadvizhki.htm" target="_blank">задвижки</a>, фланцы, оптом, Москва, каталог, прайс.</td>
</tr><tr>	<td><a href="http://www.radiodetali.com/index.htm" target="_blank"><img src="http://www.radiodetali.com/image/88-2.gif" style="width: 88px; height: 31px; border: 0px" alt="Сеть электронных компонентов"></a></td>	<td>Сеть электронных компонентов</td></tr><tr>	<td><div align="center"><a href="http://www.micro.niza.ru"><strong>www.micro.niza.ru</strong></a></div></td>	<td>Компания &quot;НИЦА&quot; занимается поставкой импортных (Philips, SGS/Thomson, FairChaild, MAXIM-Dallas, Sipex, Microchip, Telcom,HP-Agilent, Motorola, ATMEL и др.) и отечественных (&quot;Цветотрон&quot;, &quot;Интеграл&quot;, &quot;ФОТОН&quot;, &quot;НЗПП&quot;, &quot;Днепр&quot;, &quot;Планета&quot; и мн. др. отечественных производителей) радиоэлектронных компонентов со склада в Москве и под заказ. </td></tr><tr>	<td><div align="center"><a href="http://www.elfa.spb.ru"><strong>www.elfa.spb.ru</strong></a></div></td>	<td>Поставка электронных компонентов, кабелей, приборов и оборудования <strong>по каталогу ELFA</strong> (Швеция), <a href="http://www.elfa.spb.ru/links.shtml" target="_new">обмен ссылками.</a></td></tr><tr>	<td><div align="center" ><a href="http://www.dialelectrolux.ru/"><strong>dialelectrolux.ru</strong></a></div></td>	<td><span >Поставка электронных компонентов.</span></td></tr><tr>	<td><div align="center"><a href="http://www.reom.ru"><strong>www.reom.ru</strong></a></div></td>	<td>Реом - производство и поставка радиоэлектронных компонентов: резисторы, датчики, реле и пр.</td></tr><tr>	<td><!-- code radiovnimanie.ru begin -->	<div align="center"><a href="http://www.radiovnimanie.ru"><img height="31" alt="Радиовнимание: ресивер, радиостанция, GPS приемники, GPS навигаторы, рация носимая, автомобильная, базовая, бортовая, авиа и морская: Alan, Alinco, Motorola, Kenwood, Icom, Vertex, Yaesu, Maycom, Megajet; система видеонаблюдения, домофон, диктофон и другая техника для бизнеса и безопасности. Доставка по России." src="http://www.radiovnimanie.ru/radiovnimanie.gif" width="88" border="1"></a></div>	<!-- code radiovnimanie.ru end --></td>
	<td><!-- code radiovnimanie.ru begin -->
	<a href="http://www.radiovnimanie.ru"><b>ЗАО "РАДИОВНИМАНИЕ"</b> - радиостанции, GPS приемники, GPS навигаторы, рации: носимые, автомобильные, базовые, бортовые, авиа и морские:</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/Alan/1Alan-main.htm">Alan,</a>&nbsp; <a href="http://www.radiovnimanie.ru/Alinco/1Alinco-main.htm">Alinco,</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/Motorola/1Motorola-main.htm">Motorola,</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/Kenwood/1Kenwood-main.htm">Kenwood,</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/Icom/1Icom-main.htm">Icom,</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/Vertex/1Vertex-main.htm">Vertex,</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/Vertex/1Vertex-main.htm">Yaesu,</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/Maycom/1Maycom-main.htm">Maycom,</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/Megajet/1Megajet-main.htm">Megajet,</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/Standard/1Standard-main.htm">Standard,</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/Low_power/1Low-power-main.htm">маломощные рации.</a>&nbsp; 
	<a href="http://www.radiovnimanie.ru/home.htm">Системы видеонаблюдения, цифровые видеорегистраторы, домофоны, диктофоны и др. Доставка по России.</a><!-- code radiovnimanie.ru end --></td></tr><tr>	<td><a href="http://www.concernargo.ru/"><strong>concernargo.ru</strong></a></td>	<td>Продажа радиодеталей и электронных компонентов. Поставки в любые регионы России и страны СНГ в кратчайшие сроки. Бесплатно ответим на все вопросы и проведем консультации на темы, касающиеся радиоэлектроники.</td></tr><tr>	<td><a href="http://www.smd.ru/">SMD.ru</a></td>	<td>Продажа электронных компонентов для поверхностного монтажа.</td></tr><tr>	<td><strong><a href="http://www.Tabe.ru">www.Tabe.ru</a></strong></td>	<td>Оборудование для изготовления и монтажа печатных плат. Новое и восстановленное. Запасные части. Поставка со склада в Москве и на заказ.</td></tr><tr>	<td><a href="http://www.rct.ru/" target="_blank"><img src="http://rct.ru/top/88x31.gif" alt="РадиоТехТрейд" style="width: 88px; height: 31px; border: 0px"></a></td>	<td><p>РадиоТехТрейд - электронные компоненты. Оптовые поставки из Европы и Юго-Восточной Азии. <a href="http://www.rct.ru/korpus/index.shtml" target="_blank">Корпуса для РЭА</a>.</p></td></tr><tr>	<td><a href="http://www.ssd.ru/"><img src="http://www.ssd.ru/images/logo-ssd.gif" style="width: 88px; height: 31px; border: 0px" alt="СвязьСтройДеталь"></a></td>	<td>СвязьСтройДеталь. Муфта, припои, плинт, KRONE, КРТ, 3M, 3M, Raychem, УКС, кабелеискатель, колодцы, ССД. </td></tr><tr>	<td><a href="http://www.polykit.ru" target="_blank"><img src="http://www.polykit.ru/polykit3188.gif" alt="Техника для контроля и управления" style="width: 88px; height: 31px; border: 0px"></a></td>	<td>Поликит: приборы и оборудование для измерений, контроля и управления процессами в промышленности и энергетике</td></tr><tr>
	<td><strong><a href="http://www.radioweb.ru/">lainslav.narod.ru</a></strong></td>	<td>Электроника, оборудование, автоматика: оригинальные разработки предложения к сотрудничеству. </td></tr><tr>	<td><a href="http://www.business.leasat.net" target="_blank"><img src="http://www.business.leasat.net/images/busa.gif" style="width: 88px; height: 31px; border: 1px"></a></td>	<td>Поставка в Луганске: биполярные транзисторы, полевые транзисторы, микросхемы, диоды, тиристоры, светодиоды, варикапы, конденсаторы, радиолампы, резисторы, реле, герметичные контакты</td></tr><tr>	<td><a href="http://www.pribor.ru/"><strong>www.pribor.ru</strong></a></td>	<td><a href="http://www.pribor.ru/">Измерительные приборы - мегаомметры, дозиметры, осциллографы, Tektronix, SMT, SMD</a>, 
	<a href="http://www.pribor.ru/t_ob/3.html">поверхностный монтаж</a>, <a href="http://www.pribor.ru/e_ob/111.html">качество электроэнергии</a>,<a href="http://www.pribor.ru/p_ob/69.html">паяльные станции</a>, <a href="http://www.pribor.ru/k_ob/123.html">Fluke</a>, <a href="http://www.pribor.ru/e_ob/130.html">токовые клещи</a>, <a href="http://www.pribor.ru/k_ob/27.html">цифровые мультиметры</a>, <a href="http://www.pribor.ru/mebel.html">промышленная мебель</a>, <a href="http://www.pribor.ru/p_ob/66.html">паяльники</a>, <a href="http://www.pribor.ru/t_ob/4.html">печи оплавления</a>, <a href="http://www.pribor.ru/p_ob/8.html">WELLER</a>, <a href="http://www.pribor.ru/v_ob/94.html">виброметры</a>.</td> </tr><tr>	<td><div align="center"><a href="http://www.specelservis.ru/" target="_blank"><img src="http://www.specelservis.ru/banner/banner_but.gif" style="width: 88px; height: 31px; border: 1px" alt="Спецэлсервис - электронные компоненты"></a></div></td>	<td>Электронные компоненты со всего мира. Интернет-магазин, низкие цены, обширный каталог технической документации.</td>
</tr><tr>	<td><a href="www.sec-online.ru" target="_blank"> <img src="http://www.sec-online.ru/images/ban88x31.gif" style="width: 88px; height: 31px; border: 0px" alt="Саранская электронная Компания - поставка электронных компонентов"></a></td>	<td>Поставка импортных электронных и электротехнических компонентов. «СЭК» предлагает широкий ассортимент силовой электроники, микросхем, транзисторов, диодов, реле, конденсаторов и многих других комплектующих изделий.</td></tr><tr>	<td><a href="http://www.optenergo.ru"><strong>www.optenergo.ru</strong></a></td>	<td>Группа компаний Оптэнерго - сотрудничество в области поставок электротехнической продукции как российских так и зарубежных производителей - реле, контакторы, установки для компенсации реактивной мощности, преобразователи частоты, низковольтные комплектные устройства. Доставляем по России.</td></tr><tr>	<td><div align="center"><a href="http://www.partsearch.ru"><img src="http://www.partsearch.ru/butt/mig_88x31.gif" style="width: 88px; height: 31px; border: 0px" alt="Поставка электронных компонентов"></a></div></td>
	<td>МИГ Электроника. Поставка электронных компонентов.</td></tr><tr>	<td><a href="http://www.triod.kiev.ua" target="_blank"><img src="http://www.triod.kiev.ua/Triod.files/88x31.gif" alt="Триод. Лампы, магнетроны, ЛБВ, другие электровакуумные приборы" style="width: 88px; height: 31px; border: 1px" title="Триод. Ламповый сайт"></a></td>	<td>&quot;Триод&quot;. Реализация электровакуумных, коммутационных, силовых приборов и др. РЭК.</td></tr><tr>	<td><a target="_blank" href="http://oaopiezo.com"><img src="http://oaopiezo.com/banner2.gif" alt="Группа предприятий Пьезо - кварцевые резонаторы, кварцевые фильтры, кварцевые генераторы. " style="width: 88px; height: 31px; border: 0px"></a></td>	<td>Группа предприятий Пьезо. Разработка, производство и поставка пьезоэлектрических монокристаллов и изделий на их основе: кристаллические элементы, пьезоэлектрические датчики, кварцевые и лангаситовые резонаторы, кварцевые фильтры и высокостабильные кварцевые генераторы. Справочная информация по пьзотехнике.</td></tr><tr>	<td><div align="center"><a href="http://www.raciya.ru"><strong>www.raciya.ru</strong></a></div></td>	<td>Продажа радиостанций с доставкой.</td></tr>
<tr>	<td><div align="center"><a href="http://www.szemo.ru/"><strong>www.szemo.ru</strong></a></div></td>	<td>Северо-Западное Электромеханическое Объединение - насосы, вентиляторы, электродвигатели, преобразователи частоты, устройства плавного  пуска и другие средства промышленной автоматизации. Ремонт электродвигателей.</td></tr><tr>	<td><a href="http://www.gainta.com/" target="_blank"><img src="http://gainta.com/gainta88x31.gif" alt="Корпуса для РЭА GAINTA" style="width: 88px; height: 31px; border: 1px"></a></td>	<td>Интернет-магазин. Электронные компоненты. Корпуса для РЭА GAINTA. On-line заказ.</td></tr><tr>	<td><a href="http://www.sick-maihak.ru/"><img src="http://www.sick-maihak.ru/images/maihak_banner.gif" style="width: 88px; height: 31px; border: 1px"></a></td>	<td><a href="http://www.sick-maihak.ru/">Поставка оборудования для контроля, диагностики и мониторинга выбросов. Гарантийное и сервисное обслуживание</a>.</td></tr><tr>	<td><!--begin of LEDZ.org-->	<a href="http://www.ledz.org" target="_blank"><img src="http://www.ledz.org/images/banner88.gif" alt="LEDZ.org - всё о самых ярких светодиодах!" style="width: 88px; height: 31px; border: 1px"></a>	<!--begin of LEDZ.org--></td>	<td>На сайте вы найдёте много полезной информации и интересных статей о светодиодах, сможете пообщаться в форуме, а также приобрести светодиоды в нашем интернет-магазине по самым низким ценам.</td></tr>
</table>
<p><strong>Код ссылки для обмена <a href="exchange.php">здесь</a>.</strong></p>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>