/*************************************************************************

    chm2web Supply Library 1.1
    Copyright (c) 2002-2004 A!K Research Labs (http://www.aklabs.com)  
    http://chm2web.aklabs.com - HTML Help Conversion Utility

    Tested with: Internet Explorer 5, Opera 6, Mozilla 1.2, NN6

    ATTENTION! You can use this library only with web help system 
               generated by chm2web software.  
               
**************************************************************************/

function FindFrame(frameName, start)
{
 if(start==null) return null;

 var resframe = null;
 var frames = start.frames;
 if(frames.length==0) return null;

 for(var i=0; i<frames.length; i++)
 {
    tmpFrame = frames[i];
    if(tmpFrame.name.toUpperCase() == frameName.toUpperCase())
    {
      resframe = frames[i];
    } else {
      resframe = FindFrame(frameName, tmpFrame);
    }
    if (resframe != null) return resframe;
 } return null;
}

function navNext(d, page)
{
    var ar = arr_findNext(page, d);
    if (ar != "") {
      window.open(ar, "content");
      return;
    }	
}
